version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306:3306'

  php:
    image: wodby/wordpress:4-7.1
    environment:
      ENV: development
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_NAME: wordpress
      DB_USER: username
      DB_PASSWORD: password
      DB_HOST: mariadb
      WP_HOME: localhost:8000
      WP_SITEURL: localhost:8000
    volumes:
      - ./wordpress/:/var/www/html

  nginx:
    image: wodby/wordpress-nginx:4
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./wordpress/:/var/www/html
    depends_on:
      - php
      - mariadb
    ports:
      - '8000:80'
